language: node_js
node_js:
- 0.10
deploy:
  api_key:
    secure: OVpjHwJ3aqVCl0lW/x19Pw/ViNDdNljTabtNgB9/e7M9VZkBXIfvyqKPIMCtrtV96yVBaRWqFx5xNQbgScc8+MB/bTXOT6pf0dHJZ+GOMCVgl/zQp9GokgG311cC1wiSCrggQ10jb3RURjI+JpjGa3DlD8O3r7EYFKMTPju9niM=
