language: node_js
node_js:
- 0.1
deploy:
  provider: heroku
  api_key:
    secure: FthHsNwqVN+cW0ocdPxIfqOywpASRd1/HlZPY/2d6DB+2Gbf/JtBaqmb5t9Vqht9ab51VXPxw5Xw74s8FgyBhYXRXgi+pfd7S8prrfA+OSpsqw7xAZnP/dsNWMyF51+lCB4xR6XO/Zl3zeTXhHOCvpJ9HDHdBfZqBipcfXTFvKY=
  app: sailschat
  on:
    repo: BrunoAlejos/sailsChat
